# Generated by Django 2.2.9 on 2021-04-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('PayPal', 'PalPal'), ('On Delivery', 'On Delivery')], max_length=30),
        ),
    ]
