# Generated by Django 2.2.9 on 2021-04-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
