# Generated by Django 2.2.9 on 2021-04-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20210427_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('PayPal', 'PayPal'), ('On Delivery', 'On Delivery')], max_length=30),
        ),
    ]
