# Generated by Django 2.2.9 on 2021-03-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_1',
            field=models.CharField(default='Address 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_2',
            field=models.CharField(default='Address 2', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='01xxxxxxxx', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(default='postal code', max_length=6),
        ),
    ]
