# Generated by Django 2.2.9 on 2021-04-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210318_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_2',
            field=models.CharField(default='Address 2 (street, Building)', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='City', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='Phone', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(default='Postal Code', max_length=6),
        ),
    ]
