# Generated by Django 2.2.9 on 2021-04-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_users_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='Phone', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(default='Postal Code', max_length=100),
        ),
    ]
