# Generated by Django 2.2.9 on 2020-12-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20201224_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_product_live',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(max_length=100),
        ),
    ]
