# Generated by Django 2.2.9 on 2020-12-29 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20201224_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=30)),
                ('publisher_picture', models.ImageField(default='book-imgs/default.jpg', upload_to='publisher-imgs')),
                ('about_publisher', models.TextField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='long_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.AddField(
            model_name='author',
            name='about_author',
            field=models.TextField(default='Author Details', max_length=500),
        ),
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='book-imgs/default.jpg', upload_to='cat-imgs'),
        ),
        migrations.DeleteModel(
            name='product_Image',
        ),
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainsite.publisher'),
        ),
    ]
