# Generated by Django 2.2.9 on 2021-01-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_product_downloadable_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ebook',
            field=models.BooleanField(default=False),
        ),
    ]
