# Generated by Django 2.2.9 on 2021-01-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_product_ebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ebook',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
    ]
