# Generated by Django 2.2.9 on 2021-02-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_auto_20210121_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='advertising_banner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='ordered_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock_number',
            field=models.IntegerField(default=0),
        ),
    ]
