# Generated by Django 2.2.9 on 2021-02-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_auto_20210225_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='advertising_banner',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
    ]
