# Generated by Django 2.2.9 on 2021-03-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0015_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
