# Generated by Django 2.2.9 on 2021-03-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0016_auto_20210315_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='end',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=1),
        ),
    ]
