# Generated by Django 2.2.9 on 2021-03-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0020_author_author_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='born',
            field=models.IntegerField(default=2000),
        ),
    ]
