# Generated by Django 2.2.9 on 2021-04-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0023_auto_20210331_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='website_layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_dark', models.ImageField(default='book-imgs/default.jpg', upload_to='cat-imgs')),
                ('logo_light', models.ImageField(default='book-imgs/default.jpg', upload_to='cat-imgs')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
