# Generated by Django 2.2.9 on 2021-04-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0024_website_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website_layout',
            name='logo_dark',
            field=models.ImageField(default='website-layout/default.jpg', upload_to='website_layout'),
        ),
        migrations.AlterField(
            model_name='website_layout',
            name='logo_light',
            field=models.ImageField(default='website-layout/default.jpg', upload_to='website_layout'),
        ),
    ]
