# Generated by Django 2.2.9 on 2021-04-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0026_auto_20210423_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping_fee',
            name='city',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
