# Generated by Django 2.2.9 on 2021-04-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0027_auto_20210423_2000'),
    ]

    operations = [
    	migrations.RemoveField(
            model_name='product',
            name='advertising_banner',
        ),
        migrations.AddField(
            model_name='product',
            name='advertising_banner',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (2, 'No')], default=2),
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_product_live',
        ),
        migrations.AddField(
            model_name='product',
            name='is_product_live',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1),
        ),
    ]
