# Generated by Django 2.2.9 on 2020-12-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Confirmed', 'Confirmed'), ('canceled', 'canceled')], default='Waiting', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('PayPal', 'PayPal'), ('On Delivery', 'On Delivery')], default='On Delivery', max_length=50),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
