# Generated by Django 2.2.9 on 2021-02-24 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201228_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='auto_user_id',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=100),
        ),
    ]
