# Generated by Django 2.2.9 on 2021-02-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_auto_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='auto_user_id',
            field=models.IntegerField(default=1),
        ),
    ]
