# Generated by Django 2.2.9 on 2021-02-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210224_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='auto_user_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
