# Generated by Django 2.2.9 on 2021-02-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210224_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='auto_user_id',
        ),
    ]
