# Generated by Django 2.2.9 on 2021-04-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210315_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='usd_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
