# Generated by Django 2.2.9 on 2021-04-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_usd_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Delivering', 'Delivering'), ('Delivered', 'Delivered'), ('canceled', 'canceled')], default='Waiting', max_length=50),
        ),
    ]
